-- ============================================
-- SQL para insertar USUARIO DE PRUEBA
-- CC: 111111
-- Contraseña: prueba
-- Comunas de Ibagué (13 comunas)
-- ============================================

-- ============================================
-- SQL para insertar USUARIO DE PRUEBA
-- CC: 111111
-- Contraseña: prueba
-- Comunas de Ibagué (13 comunas) y sus barrios
-- ============================================

-- PASO 0: Insertar comunas de Ibagué
INSERT INTO komerizo_comunas (nombre)
VALUES
  ('Comuna 1'),
  ('Comuna 2'),
  ('Comuna 3'),
  ('Comuna 4'),
  ('Comuna 5'),
  ('Comuna 6'),
  ('Comuna 7'),
  ('Comuna 8'),
  ('Comuna 9'),
  ('Comuna 10'),
  ('Comuna 11'),
  ('Comuna 12'),
  ('Comuna 13')
ON CONFLICT (nombre) DO NOTHING;

-- PASO 0.5: Insertar barrios por comuna
-- Comuna 1 (11 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Augusto E. Medina', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Baltazar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Centro', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Combeima', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Estación', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Interlaken', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('La Pola', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('La Pola Parte Alta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Libertador', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('Pueblo Nuevo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1')),
('San Pedro Alejandrino', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 1'))
ON CONFLICT DO NOTHING;

-- Comuna 2 (21 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('20 de Julio', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('7 de Agosto', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Alaska', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Ancón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Belén', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Belencito', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Centenario', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Clarita Botero', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Irazú', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('La Aurora', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('La Sofía', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('La Paz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('La Trinidad', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Malabar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Paraíso', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('San Diego', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Santa Bárbara', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Santa Cruz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Villa Adriana', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2')),
('Viña de Calambeo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 2'))
ON CONFLICT DO NOTHING;

-- Comuna 3 (17 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Antonio Nariño', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Belalcazar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Calambeo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Carmenza Rocha', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('El Carmen', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Fenalco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Gaitán Parte Alta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('INEM', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('La Esperanza', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('La Granja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Las Acacias', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('San Simón Parte Alta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('San Simón Parte Baja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Villa Ilusión', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Villa Pinzón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Villa Valentina', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3')),
('Viveros', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 3'))
ON CONFLICT DO NOTHING;

-- Comuna 4 (25 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Alfonso López', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Calarcá', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Cámbulos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Caracolí', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Castilla', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Gaitán', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Jacaranda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('José María Córdoba', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('José María Córdoba Parte Baja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Limonar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Limonar V Sector', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Onzaga', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Piedra Pintada', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Pijao', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Restrepo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Rincón de Piedra Pintada', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('San Carlos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('San Luis', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Sorrento', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Toscana', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Triunfo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Villa Marlen I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Villa Marlen II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Villa Teresa', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4')),
('Las Viudas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 4'))
ON CONFLICT DO NOTHING;

-- Comuna 5 (32 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Jordán Etapa IV', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Jordán Etapa VI', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Jordán Etapa VII', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Jordán Etapa VIII', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Jordán Etapa IX', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Arkalucía', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Arboleda Margaritas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Arkacentro', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Arkamónica', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Arrayanes', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Calatayud', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Conjunto Residencial La Alameda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Cordobita', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('El Edén', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('La Campiña', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('La Ladera', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Las Margaritas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Las Orquídeas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Macadamia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Multifamiliares El Jordán', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Multifamiliares Las Margaritas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Prados del Norte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Rincón de la Campiña', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('San Jacinto', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Torre Ladera', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Aymará I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Aymará II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Rincón de las Margaritas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Los Ocobos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Millenium I y II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Yacaira', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5')),
('Urbanización Los Parrales', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 5'))
ON CONFLICT DO NOTHING;

-- Comuna 6 (60+ barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Agua Viva', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Altos de San Francisco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Balcones del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Bosques del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Brisas del Pedregal', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Cañaveral I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Cañaveral II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Caminos de San Juan Pablo II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Caminos de San Francisco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Caminos del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('El Mirador', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('El Triunfo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Estancia del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Fuente de los Rosales I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Fuente de los Rosales II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('La Balsa', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('La Esperanza', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('La Gaviota', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Las Delicias', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Los Alpes', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Los Ángeles', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Los Ciruelos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Los Mandarinos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Montemadero', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Monte Verde del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Palma del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Paseo de San Francisco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Plazas del Bosque', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Portal del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Primavera de Entre Ríos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Reservas del Pedregal', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Rincón de San Francisco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Rincón del Pedregal I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Rincón del Pedregal II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Rincon del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('San Antonio', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Tierra Linda del Vergel', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Torre Fuente de los Rosales', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Torres de la Calleja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Villa Gloria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Altos de Ambalá', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Altos de Pedregal', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Ambalá', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Antares I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Antares II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Arkalá I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Arkalá II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Arkambuco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Chicalá', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Colinas del Norte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Entre Ríos I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Entre Ríos II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Fuente de los Rosales I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Girasol', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Ibagué 2000', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Los Cámbulos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Los Gualandayes', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Pedregal', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Villa Patricia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6')),
('Urbanización Villa Vanesa', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 6'))
ON CONFLICT DO NOTHING;

-- Comuna 7 (63 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Álamos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Chicó', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('El Salado', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Hacienda El Recreo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Los Músicos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Mirador de Cantabria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Modelia I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Modelia II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Nueva Bilbao', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Pedro Ignacio Villamarín', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Rosales de Tailandia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Santa Ana', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Sector Los Alpes', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Timaka', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Santa Coloma', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Alameda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Carlos Lleras Camargo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Ambikaima', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Cantabria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Comfatolima', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Diana Milaidy', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización El Dorado', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización El Limón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización El Palmar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Fuente del Salado', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Fuente Santa', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización La Cabaña', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización La Candelaria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización La Floresta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización La Victoria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Lady Di', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Los Lagos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Monte Carlos II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Oviedo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Pacandé', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Palma del Río', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Palo Grande', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Portales del Norte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Praderas del Norte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Reservas de Cantabria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización San Luis', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización San Luis Gonzaga', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización San Luisú', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización San Pablo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización San Sebastián', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Santa Catalina I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Santa Mónica', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Shaddai', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Territorio de Paz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Tierra Firme', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Brasilia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Camila', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Cindy', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Clara I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Clara II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Julieta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Rocío', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Sulay', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización La Ceiba Norte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Urbanización Villa Martha', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Villa Salomé', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7')),
('Villa Suiza', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 7'))
ON CONFLICT DO NOTHING;

-- Comuna 8 (70+ barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Atolsure', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Caminos del Bosque', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Ciudadela Simón Bolívar I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Ciudadela Simón Bolívar II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Ciudadela Simón Bolívar III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Conjunto Residencial San Joaquín', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('El Bunde I, II y III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('El Bunde IV', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Germán Huertas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Jardín I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Jardín III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Jardín Parte Baja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Jardín Santander I, II, III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Jardín Valparaíso', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('La Cima I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('La Cima II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('La Cima III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('La Florida', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Musicalia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Palermo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Portal del Jardín', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Reservas del Jardín', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Roberto Augusto Calderón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('San Gelato', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Topacio', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Tulio Varón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Unidad Residencial Carabineros', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización 2 de Junio', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Agua Marina', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Altos de Vasconia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Antonio María', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Brisas de Vasconia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Buenaventura García', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Ciudad Blanca', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización El Palmar I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización El Palmar II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización El Prado I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización El Prado II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín Atolsure', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín Avenida V', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín Chipalo I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín Chipalo II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín Porvenir', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardín VI', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Jardines del Campo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización La Esmeralda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Las Acacias', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Los Comuneros', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Los Laureles', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Los Pinos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Nueva Castilla', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Nueva Colombia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Nuevo Armero', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Nuevo Combeima', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Nuevo Combeima II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Portal de Arkalá', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Protecho', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Quinta Avenida', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Tolima Grande', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Vasconia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Vasconia Reservado', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa del Norte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa del Palmar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa del Sol', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa Esperanza', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa Jardín', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa La Paz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa Magdalena', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa Marcela', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Urbanización Villa Vicentina', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Villa Cristales', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8')),
('Yerbabuena', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 8'))
ON CONFLICT DO NOTHING;

-- Comuna 9 (60+ barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Alfonso Uribe Badillo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Altamira', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Aparco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Arboleda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Arboleda Campestre', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Arkaniza I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Arkaniza II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Arkaparaiso', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Bello Horizonte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Bosque de la Alameda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Carrenales', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Condominio Las Palmeras', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Conjunto Residencial Valparaíso', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('El Tunal', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Hacienda Piedra Pintada', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Hacienda Santa Cruz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Honda', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Jordán I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Jordán II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Jordán III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('La Floresta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('La Samaria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Los Tunjos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Picaleña', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Picaleñita', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Portal de Los Tunjos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Villa Luz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Reservas del Campestre', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('San Francisco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('San Martin', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('San Remo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Bosque de Varsovia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Chaquén', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Ciudad Luz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Comfenalco', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Coopdiasan', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Cutucumay', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización El Poblado', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Las Américas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Las Flores', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Los Remansos', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Miraflores', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Nuevo Horizonte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Portal Campestre', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Praderas de Santa Rita', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Tahití', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Varsovia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Villa Arkadia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Villa Café', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Villa de La Candelaria', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Villa Luz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Villa Yuli', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Urbanización Villas De Gualara', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Valparaíso I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Valparaíso II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Valparaíso III', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Valparaíso IV', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Versalles', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Villa Carvajalita', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Villa del Pilar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Villa María', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9')),
('Villa Natalia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 9'))
ON CONFLICT DO NOTHING;

-- Comuna 10 (29 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('1 de Mayo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Altos de Santa Helena', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('América', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Boyacá', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Cádiz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Casa Club', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Claret', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Departamental', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Federico Lleras', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Hipódromo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('La Francia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('La Macarena Parte Alta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('La Macarena Parte Baja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Las Palmas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Magisterio', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Montealegre', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Nacional', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Naciones Unidas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('San Cayetano', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Santa Helena', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('El Papayo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Arkalena', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Bosques de Santa Helena', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('La Castillana', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Metaima I', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Metaima II', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Santander', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Laureles', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10')),
('Altamira', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 10'))
ON CONFLICT DO NOTHING;

-- Comuna 11 (25 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('12 de Octubre', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Alto de la Cruz', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Arado', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('América', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Bosque Parte Alta', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Bosque Parte Baja', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('El Palmar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Garzón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Independiente', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('La Isla', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('La Martinica', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Las Brisas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Las Ferias', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Libertad', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Los Mártires', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Peñón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Popular', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Refugio 1', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Refugio 2', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Rodríguez Andrade', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('San Vicente de Paul', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Uribe Uribe', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Villa del Río', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Villa María', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11')),
('Los Mártires', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 11'))
ON CONFLICT DO NOTHING;

-- Comuna 12 (24 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Andrés López de Galarza', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Avenida', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Colonias de Asprovi', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Galán', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Industrial', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Kennedy', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('La Gaitana', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('La Pradera', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('La Reforma', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Las Vegas', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Matallana', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Lotus', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Murillo Toro', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Ricaurte', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Rosa Badillo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Santofimio', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Arkaima', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Divino Niño', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Terrazas del Tejar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Venecia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Villa Claudia', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Villa Luces', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Yuldaima', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12')),
('Casco Antiguo', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 12'))
ON CONFLICT DO NOTHING;

-- Comuna 13 (15 barrios)
INSERT INTO komerizo_barrios (nombre, comuna_id) VALUES
('Albania', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Boquerón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Cerros de Granate', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Colinas 1', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Colinas 2', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Colinas del calamar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Darío Echandía', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Granada', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Isla', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Jazmín', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('La Unión', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Miramar', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('San Isidro', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Terrazas de Boquerón', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13')),
('Villa Mery', (SELECT id FROM komerizo_comunas WHERE nombre = 'Comuna 13'))
ON CONFLICT DO NOTHING;

-- PASO 1: Insertar tipos de documento
INSERT INTO komerizo_tipo_documento (nombre, abreviatura) 
VALUES 
  ('Cédula de Ciudadanía', 'CC'),
  ('Cédula de Extranjería', 'CE'),
  ('Pasaporte', 'PA'),
  ('NIT', 'NIT')
ON CONFLICT (abreviatura) DO NOTHING;

-- PASO 2: Insertar usuario de prueba
INSERT INTO komerizo_usuarios (
  cc,
  tipo_documento_id,
  nombre,
  apellido,
  correo_electronico,
  contrasena,
  telefono,
  direccion,
  jac,
  estado,
  firma
) VALUES (
  '111111',
  1,
  'Juan',
  'Prueba',
  'juan.prueba@test.com',
  'prueba',
  '3001234567',
  'Calle 123 #45-67',
  'JAC Barrio Test',
  'activo',
  true
);

-- PASO 3: Insertar roles (si no existen)
INSERT INTO komerizo_roles (nombre, descripcion)
VALUES
  ('Junta Directiva', 'Miembro de la junta directiva'),
  ('Tesorero', 'Responsable de finanzas'),
  ('Secretario', 'Responsable de actas'),
  ('Vocal', 'Vocal de la JAC'),
  ('Administrador', 'Administrador del sistema'),
  ('Miembro', 'Miembro regular de la JAC')
ON CONFLICT (nombre) DO NOTHING;

-- PASO 4: Asignar rol de Miembro al usuario de prueba
INSERT INTO komerizo_usuario_roles (usuario_id, rol_id)
SELECT 
  (SELECT id FROM komerizo_usuarios WHERE cc = '111111'),
  (SELECT id FROM komerizo_roles WHERE nombre = 'Miembro')
WHERE NOT EXISTS (
  SELECT 1 FROM komerizo_usuario_roles 
  WHERE usuario_id = (SELECT id FROM komerizo_usuarios WHERE cc = '111111')
);

-- ============================================
-- Verificar que el usuario fue creado correctamente
-- ============================================
-- SELECT * FROM komerizo_usuarios WHERE cc = '111111';
-- SELECT * FROM komerizo_usuario_roles WHERE usuario_id = (SELECT id FROM komerizo_usuarios WHERE cc = '111111');
